# Some useful dict kys to set if you are scripting and running lots of data
# If only using basic examples, this is not needed.

tle_files:
  tle_directory:
  tle_storage_directory:
raw_ceres_data:
  raw_dataset_directory:
  file_to_process:
pickel_directory:
